module.exports = {
  storeMissingTax: {
    name: 'test_store',
    email: 'test_store@email.com',
    phone: '1111',
    street_address: 'test address',
    city: 'test city',
    state: 'test state',
    zipcode: '1111',
    merchant_id_ein: 'test mid',
    store_identifier: 'test store identifier',
  },
  storeNegativeTax: {
    name: 'test_store',
    email: 'test_store@email.com',
    phone: '1111',
    street_address: 'test address',
    city: 'test city',
    state: 'test state',
    zipcode: '1111',
    merchant_id_ein: 'test mid',
    store_identifier: 'test store identifier',
    tax: '-10',
  },
  storeInvalidTax: {
    name: 'test_store',
    email: 'test_store@email.com',
    phone: '1111',
    street_address: 'test address',
    city: 'test city',
    state: 'test state',
    zipcode: '1111',
    merchant_id_ein: 'test mid',
    store_identifier: 'test store identifier',
    tax: 'abc',
  },
  storeZeroTax: {
    name: 'test_store',
    email: 'test_store@email.com',
    phone: '1111',
    street_address: 'test address',
    city: 'test city',
    state: 'test state',
    zipcode: '1111',
    merchant_id_ein: 'test mid',
    store_identifier: 'test store identifier',
    tax: 0,
  },
  storeValidTax: {
    name: 'test_store',
    email: 'test_store@email.com',
    phone: '1111',
    street_address: 'test address',
    city: 'test city',
    state: 'test state',
    zipcode: '1111',
    merchant_id_ein: 'test mid',
    store_identifier: 'test store identifier',
    tax: 10,
  },
};
